{
 "title": "GCP Cost and Usage",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "table_id", "label": "Table ID", "query": "${VAR_TABLE_ID}" },
   { "name": "project_id", "label": "Project ID", "query": "${VAR_PROJECT_ID}" },
   { "name": "dataset_id", "label": "Dataset_id", "query": "${VAR_DATASET_ID}" }
  ]
 },
 "panels": [
  {
   "title": "Total $ per month",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "EU",
     "project": "${VAR_PROJECT}",
     "rawSql": "SELECT\n  invoice.month,\n  (SUM(CAST(cost AS NUMERIC))\n    + SUM(IFNULL((SELECT SUM(CAST(c.amount AS NUMERIC))\n                  FROM UNNEST(credits) AS c), 0)))\n    AS total_exact\nFROM `$project_id.$dataset_id.$table_id`\nGROUP BY 1\nORDER BY 1 ASC\n;"
    }
   ]
  },
  {
   "title": "Monthly comulative spend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "EU",
     "project": "${VAR_PROJECT}",
     "rawSql": "WITH daily_data AS (\n  SELECT usage_start_time, cost,\n         SUM(cost) OVER (PARTITION BY \tinvoice.month  \n         ORDER BY usage_start_time) AS month_cumulative_sum\n  FROM `$project_id.$dataset_id.$table_id`\n)\nSELECT usage_start_time, cost,\n       CASE WHEN month_cumulative_sum = 0 THEN cost\n            ELSE cost + month_cumulative_sum END AS daily_cumulative_sum\nFROM daily_data\nORDER BY usage_start_time;"
    }
   ]
  },
  {
   "title": "Spent on GCP by SKU",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "EU",
     "project": "${VAR_PROJECT}",
     "rawSql": "SELECT\n  $__timeGroup(usage_start_time,6h),\n  sku.description AS metric,\n  SUM(cost) AS cost\nFROM\n  `$project_id.$dataset_id.$table_id`\nWHERE\n  project.id LIKE '$project_id'\n  AND sku.description IN (\n  SELECT\n    sku.description\n  FROM\n    `$project_id.$dataset_id.$table_id`\n  WHERE\n    project.id IS NOT NULL\n    AND project.id LIKE '$project_id'\n    AND $__timeFilter(usage_start_time)\n      GROUP BY\n    1\n      ORDER BY\n      SUM(cost) DESC,\n    1)\n  AND $__timeFilter(usage_start_time)\n  GROUP BY 1,2\n  ORDER BY 1 ASC"
    }
   ]
  }
 ]
}